/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-05-13 21:03:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Event Registration Form</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"homestyle.css\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Concert+One&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Audiowide&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Young+Serif&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Audiowide&family=Roboto+Slab&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<style>\r\n");
      out.write(".success-message {\r\n");
      out.write("	color: green;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".error-message {\r\n");
      out.write("	color: red;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"full\">\r\n");
      out.write("		<header>\r\n");
      out.write("			<a class=\"logo\" href=\"#\"> <span>Plan Perfect</span></a>\r\n");
      out.write("			<nav>\r\n");
      out.write("				<ul class=\"nav_link\">\r\n");
      out.write("					<li><a class=\"navii\" href=\"Home.jsp\">Home</a></li>\r\n");
      out.write("					<li><a class=\"navii\" href=\"#\">Service</a></li>\r\n");
      out.write("					<li><a class=\"navii\" href=\"#\">Contact Us</a></li>\r\n");
      out.write("					<li><a class=\"navii\" href=\"#\">About Us</a></li>\r\n");
      out.write("					<li><a class=\"navii\" href=\"#\">My Events</a></li>\r\n");
      out.write("					<li><a class=\"navii\" href=\"logout.jsp\">Logout</a></li>\r\n");
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</header>\r\n");
      out.write("		<section>\r\n");
      out.write("			<h1>Event Registration Form</h1>\r\n");
      out.write("		</section>\r\n");
      out.write("		<form action=\"servlet\" method=\"POST\" onsubmit=\"return validateForm()\">\r\n");
      out.write("			<label for=\"firstName\">First Name:</label> \r\n");
      out.write("			<input type=\"text\" id=\"firstName\" name=\"fname\"><br> <br> \r\n");
      out.write("		    <label for=\"lastName\">Last Name:</label> \r\n");
      out.write("		    <input type=\"text\" id=\"lastName\" name=\"lname\"><br> <br> <label for=\"address\">Address:</label>\r\n");
      out.write("			<input type=\"text\" id=\"address\" name=\"address\"><br> <br>\r\n");
      out.write("			<label for=\"contactNumber\">Contact Number:</label> \r\n");
      out.write("			<input type=\"tel\" id=\"contactNumber\" name=\"contactno\"><br> <br> \r\n");
      out.write("			<label for=\"eventType\">Event Type:</label> \r\n");
      out.write("			<select id=\"eventType\" name=\"type\">\r\n");
      out.write("				<option value=\"\">Select event type</option>\r\n");
      out.write("				<option value=\"Wedding\">Wedding</option>\r\n");
      out.write("				<option value=\"Birthday\">Birthday</option>\r\n");
      out.write("				<option value=\"Concert\">Concert</option>\r\n");
      out.write("				<option value=\"Private Parties\">Private Parties</option>\r\n");
      out.write("				<option value=\"Corporate Event\">Corporate Event</option>\r\n");
      out.write("				<option value=\"Other\">Other</option>\r\n");
      out.write("			</select><br> <br> \r\n");
      out.write("			<label for=\"eventVenue\">Event Venue:</label> \r\n");
      out.write("			<input type=\"text\" id=\"eventVenue\" name=\"venue\"><br> <br>\r\n");
      out.write("			<label for=\"eventDateTime\">Event Date & Time:</label> \r\n");
      out.write("			<input type=\"datetime-local\" id=\"eventDateTime\" name=\"date\"><br><br><br>\r\n");
      out.write("			<label for=\"participants\">Participants:</label> \r\n");
      out.write("			<input type=\"number\" id=\"participants\" name=\"participants\"><br>\r\n");
      out.write("			<label for=\"budget\">Budget:</label> \r\n");
      out.write("			<input type=\"number\" id=\"budget\" name=\"budget\"><br> <br> \r\n");
      out.write("			<input type=\"submit\" value=\"Submit\">\r\n");
      out.write("		</form>\r\n");
      out.write("		<div id=\"successMessage\" class=\"success-message\"\r\n");
      out.write("			style=\"display: none;\">Event registered successfully!</div>\r\n");
      out.write("		<div id=\"errorMessage\" class=\"error-message\" style=\"display: none;\">Failed\r\n");
      out.write("			to register event. Please try again.</div>\r\n");
      out.write("		<footer>\r\n");
      out.write("			<div class=\"section3\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col\">\r\n");
      out.write("						<div class=\"para\">\r\n");
      out.write("							<h1 class=\"logo1\">Plan Perfect</h1>\r\n");
      out.write("							<p>\"Experience seamless event planning with [Website Name].\r\n");
      out.write("								Explore tailored venues, vendors, and services. Let's bring your\r\n");
      out.write("								vision to life effortlessly. Join us today!\".</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col\">\r\n");
      out.write("						<div class=\"office\">\r\n");
      out.write("							<h2>Office</h2>\r\n");
      out.write("							<h4>Main Branch:</h4>\r\n");
      out.write("							<p>New Kandy road, Malabe Colombo, Srilanka.</p>\r\n");
      out.write("							<span class=\"email-id\">abcd@gmail.com</span>\r\n");
      out.write("							<h3>+94 076543210</h3>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col\">\r\n");
      out.write("						<div class=\"links\">\r\n");
      out.write("							<h2>Links</h2>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"#\">Home</a></li>\r\n");
      out.write("								<li><a href=\"#\">My Events</a></li>\r\n");
      out.write("								<li><a href=\"#\">FAQ's</a></li>\r\n");
      out.write("								<li><a href=\"#\">Privacy policy</a></li>\r\n");
      out.write("								<li><a href=\"#\">Terms and Condition</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col\">\r\n");
      out.write("						<div class=\"socialicons\">\r\n");
      out.write("							<h2>Follow Us</h2>\r\n");
      out.write("							<a href=\"https://web.facebook.com/?_rdc=1&_rdr\"><i\r\n");
      out.write("								class=\"fa-brands fa-facebook\"></i></a> <a\r\n");
      out.write("								href=\"https://www.instagram.com/\"><i\r\n");
      out.write("								class=\"fa-brands fa-instagram\"></i></a> <a\r\n");
      out.write("								href=\"https://twitter.com/home\"><i\r\n");
      out.write("								class=\"fa-brands fa-twitter\"></i></a> <a href=\"#\"><i\r\n");
      out.write("								class=\"fa-brands fa-google-plus\"></i></a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</footer>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write("		function validateForm() {\r\n");
      out.write("\r\n");
      out.write("			var firstName = document.getElementById(\"firstName\").value.trim();\r\n");
      out.write("			if (firstName == \"\") {\r\n");
      out.write("				alert(\"Please enter your first name\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			var lastName = document.getElementById(\"lastName\").value.trim();\r\n");
      out.write("			if (lastName == \"\") {\r\n");
      out.write("				alert(\"Please enter your last name\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			var address = document.getElementById(\"address\").value.trim();\r\n");
      out.write("			if (address == \"\") {\r\n");
      out.write("				alert(\"Please enter your address\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			var contactNumber = document.getElementById(\"contactNumber\").value\r\n");
      out.write("					.trim();\r\n");
      out.write("			if (contactNumber == \"\") {\r\n");
      out.write("				alert(\"Please enter your contact number\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			var contactRegex = /^\\d+$/;\r\n");
      out.write("			if (!contactRegex.test(contactNumber)) {\r\n");
      out.write("				alert(\"Please enter a valid contact number (only digits allowed)\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			if (contactNumber.length !== 10) {\r\n");
      out.write("				alert(\"Contact number must be 10 digits long\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			var eventType = document.getElementById(\"eventType\").value;\r\n");
      out.write("			if (eventType == \"\") {\r\n");
      out.write("				alert(\"Please select an event type\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			var eventVenue = document.getElementById(\"eventVenue\").value.trim();\r\n");
      out.write("			if (eventVenue == \"\") {\r\n");
      out.write("				alert(\"Please enter the event venue\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			var eventDateTime = document.getElementById(\"eventDateTime\").value\r\n");
      out.write("					.trim();\r\n");
      out.write("			if (eventDateTime == \"\") {\r\n");
      out.write("				alert(\"Please select the event date and time\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("		    var currentDate = new Date();\r\n");
      out.write("		    var eventDateTime = new Date(document.getElementById(\"eventDateTime\").value); \r\n");
      out.write("\r\n");
      out.write("		    \r\n");
      out.write("		    if (eventDateTime < currentDate) {\r\n");
      out.write("		        alert(\"Please select a future date and time for the event\");\r\n");
      out.write("		        return false;\r\n");
      out.write("		    }\r\n");
      out.write("\r\n");
      out.write("			var participants = document.getElementById(\"participants\").value\r\n");
      out.write("					.trim();\r\n");
      out.write("			if (participants == \"\") {\r\n");
      out.write("				alert(\"Please enter the number of participants\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			if (!contactRegex.test(participants)) {\r\n");
      out.write("				alert(\"Please enter a valid number of participants (only digits allowed)\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			var budget = document.getElementById(\"budget\").value.trim();\r\n");
      out.write("			if (budget == \"\") {\r\n");
      out.write("				alert(\"Please enter the budget\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			var budgetRegex = /^\\d+(\\.\\d{1,2})?$/;\r\n");
      out.write("			if (!budgetRegex.test(budget)) {\r\n");
      out.write("				alert(\"Please enter a valid budget amount (e.g., 1000 or 1000.00)\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			return true;\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
